FROM ruby:2.7.2

ENV TAG=Latest

WORKDIR /app

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update  \
    && apt-get install -y nodejs yarn \
    && rm -rf /var/lib/apt/lists/*

COPY . /app/

EXPOSE 3000

ENTRYPOINT ["sh", "entrypoint.sh"]